Define shooter motor IDs
Team1559/2024-Crescendo pull request #30
Opened 2024-02-10 21:49 UTC by SWDevilTech

2024-02-10 21:58 UTC, BrandonDudek approved these changes

2024-02-10 22:00 UTC, BrandonDudek requested changes
I think `AIMER_ENCODER_PORT` needs to be assigned.

2024-02-11 20:30 UTC, mmarchetti commented
> I think `AIMER_ENCODER_PORT` needs to be assigned.

Maybe it could use a comment, but the aimer encoder is in port 0.

2024-02-12 17:47 UTC, BrandonDudek approved these changes

2024-02-12 20:03 UTC, merged